/// Flutter icons EDLIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EDLIcons
///      fonts:
///       - asset: fonts/EDLIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EDLIcons {
  EDLIcons._();

  static const _kFontFam = 'EDLIcons';
  static const _kFontPkg = null;

  static const IconData edlRight = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edlLeft = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
